name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # ou 'main' selon votre branche par défaut

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4 # Mise à jour vers v4

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Mise à jour vers v4
        with:
          node-version: '20' # Version de Node.js LTS

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # La branche où sera publié le site
          folder: dist # Le dossier contenant le site construit
